# Originally Fresh-session work package, Phase 4e: golden-file generator
# for the two new auto-fit modes. RETARGETED 2026-09-01 (thesis_notes.md
# "Production sideslip source set to ekf_auto_pacejka"): ekf_auto_pacejka
# is now generated by the retargeted tests/generate_golden.py (primary
# mode, asserts the live config equals it); this script now generates the
# two SECONDARY, explicit-mode golden files -- "kinematic" and
# "ekf_auto_dugoff" -- each passed to resolve_sideslip_beta by name,
# independent of whatever the live config's sideslip_source is set to.
# NOT a test itself (pytest does not collect this file). Run manually and
# deliberately:
#   python -m tests.generate_golden_auto_modes
#
# Will not overwrite a golden file that already exists -- delete it first
# if you intend to regenerate deliberately (same guard as the retargeted
# tests/generate_golden.py, added 2026-09-01 so a routine re-run can never
# silently reset a pinned baseline's provenance).
#
# REGRESSION, NOT CORRECTNESS -- same caveat as tests/generate_golden.py.
# Uses modules.tyre_fit_auto.resolve_sideslip_beta (the real production
# wiring function, not a reimplementation) so these goldens pin what
# production actually computes, not an idealised version of it.

import datetime
import json
import os
import subprocess

import numpy as np

from modules.csv_parser import parse_csv
from modules.stability_analysis import (
    load_parameters, prepare_vehicle_state,
    estimate_slip_angles, estimate_lateral_forces, estimate_cornering_stiffness,
    estimate_yaw_moment_stability, estimate_vertical_loads, summarise_corners,
)
from modules.accuracy_resolution import resolve_accuracy, apply_resolved_vehicle
from modules.tyre_fit_auto import resolve_sideslip_beta

RAW_FILE = "C:/UNI/Bachelorarbeit/Data/Sample/Sample_Dubai.txt"
FIXED_CAP = 1
GOLDEN_PATHS = {
    "kinematic": "tests/golden/pipeline_dubai_kinematic_cap1.json",
    "ekf_auto_dugoff": "tests/golden/pipeline_dubai_ekf_auto_dugoff_cap1.json",
}


def _git_hash():
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"], capture_output=True, text=True, check=True
        ).stdout.strip()
    except Exception as e:
        return f"UNAVAILABLE ({e})"


def _numpy_safe(obj):
    if isinstance(obj, dict):
        return {k: _numpy_safe(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_numpy_safe(v) for v in obj]
    if isinstance(obj, (np.floating,)):
        return float(obj)
    if isinstance(obj, (np.integer,)):
        return int(obj)
    if isinstance(obj, (np.bool_,)):
        return bool(obj)
    return obj


def main():
    params = load_parameters()
    resolved = resolve_accuracy(params, setup_data=None, cap=FIXED_CAP)
    effective_params = apply_resolved_vehicle(params, resolved)
    data = parse_csv(RAW_FILE)
    state = prepare_vehicle_state(data["channels"], effective_params)

    for mode, path in GOLDEN_PATHS.items():
        if os.path.exists(path):
            print(f"skipping {path} (already exists) -- delete it first to regenerate deliberately")
            continue

        beta, fit_manifest, gate_verdict, fallback_used, fallback_reason = resolve_sideslip_beta(
            state, effective_params, data, mode, csv_path=RAW_FILE
        )
        if fallback_used and mode != "ekf_auto_dugoff":
            raise SystemExit(
                f"refusing to generate a golden file for {mode!r} while it fell back to kinematic "
                f"({fallback_reason}) -- this mode is not currently 'ok' on Dubai, generating a "
                f"golden under a fallback would silently pin the WRONG estimator's numbers"
            )
        if fallback_used:
            # CS validity repair, Phase 4 (2026-09-02, thesis_notes.md
            # "Threshold anchoring + arc closure, Phase 4"): ekf_auto_
            # dugoff's rear-axle mu_fz fit degenerates on Dubai under the
            # final CS window floor (100 Hz grid) and falls back to
            # kinematic beta on every run -- a designed, loud, non-silent
            # fallback (modules/nis_gate.py's own gate never even runs;
            # the degeneracy is caught earlier, in the fit itself), not a
            # bug. Pinning the fallback path here is deliberate: it is
            # production's own current, correct behaviour for this mode
            # on this file, and this golden documents exactly that.
            print(f"NOTE: {mode!r} fell back to kinematic ({fallback_reason}) -- "
                  f"pinning the fallback path deliberately, this is designed behaviour "
                  f"for ekf_auto_dugoff on Dubai, see thesis_notes.md")
        slip = estimate_slip_angles(state, beta, effective_params)
        forces = estimate_lateral_forces(state, effective_params)
        cs = estimate_cornering_stiffness(slip, forces, state, effective_params)
        stab = estimate_yaw_moment_stability(state, beta, effective_params, data.get("laps", []))
        fz = estimate_vertical_loads(state, forces, effective_params)
        corners = data.get("corners", [])
        summaries = summarise_corners(corners, cs, stab, state, fz=fz, lap_filter=None)

        purpose = ("REGRESSION baseline, not a correctness claim -- see "
                   "tests/test_golden_auto_modes.py's module docstring. SECONDARY mode "
                   "(ekf_auto_pacejka is primary, generated separately by "
                   "tests/generate_golden.py). For ekf_auto_dugoff the underlying tyre "
                   "curve is fit fresh on this data every time "
                   "modules.tyre_fit_auto.fit_session runs -- this golden pins CURRENT "
                   "fit-chain output, not a frozen prior-session curve. For kinematic it "
                   "is the fixed production estimate_sideslip, unchanged run to run.")
        if fallback_used:
            purpose += (
                " PINS THE FALLBACK PATH DELIBERATELY (CS validity repair, Phase 4, "
                "2026-09-02): ekf_auto_dugoff's rear-axle mu_fz fit degenerates on Dubai "
                "under the final CS window floor (100 Hz grid) and this golden's own "
                "summaries are therefore KINEMATIC beta's output, not a Dugoff fit -- "
                "see fallback_reason below and thesis_notes.md 'Threshold anchoring + "
                "arc closure, Phase 4' for the full record. This is designed behaviour, "
                "not a golden-generation bug.")
        payload = {
            "_meta": {
                "purpose": purpose,
                "git_commit_hash": _git_hash(),
                "generated_at_utc": datetime.datetime.now(datetime.timezone.utc).isoformat(),
                "data_file": RAW_FILE,
                "sideslip_source": mode,
                "accuracy_cap": FIXED_CAP,
                "setup_data": None,
                "fit_manifest": fit_manifest,
                "gate_verdict": gate_verdict,
                "fallback_used": fallback_used,
                "fallback_reason": fallback_reason,
            },
            "summaries": summaries,
        }
        with open(path, "w", encoding="utf-8") as f:
            json.dump(_numpy_safe(payload), f, indent=2, allow_nan=True)
        gate_text = gate_verdict["verdict"] if gate_verdict is not None else "n/a (kinematic, no gate)"
        print(f"wrote {path} ({len(summaries)} corner summaries, gate={gate_text})")


if __name__ == "__main__":
    main()
