# Phase 1 -- golden-value regression on the full production chain and on
# the recommendation engine.
#
# THESE ARE REGRESSION TESTS, NOT CORRECTNESS TESTS. They pin CURRENT
# output (tests/golden/*.json, generated by tests/generate_golden.py) so
# a future code change that alters the numbers is VISIBLE. A passing
# suite means "nothing changed unintentionally" -- it never means "the
# numbers are correct". Some of what is pinned here may still be wrong;
# thesis_notes.md and PLAN.md's own record of known limitations (the
# kinematic sideslip circularity, the CS_ratio cross-lap aggregation
# ceiling-clipping problem, the un-re-derived thresholds) are exactly the
# kind of thing a golden test happily pins without endorsing.
#
# Golden files record: git commit hash, generation timestamp, and the
# exact configuration (sideslip_source, accuracy cap, config snapshot) --
# see tests/generate_golden.py and each golden file's own "_meta" block,
# so a future failure can be attributed to either a real behaviour change
# or a deliberate, intentional regeneration.
#
# Float tolerance and NaN handling: see tests/_json_utils.py's own
# docstring/comments for the full rationale (combined relative+absolute
# tolerance, rtol=1e-6/atol=1e-9; NaN==NaN passes, NaN-vs-number fails).

import json

import pytest

from tests._json_utils import diff_json

PIPELINE_GOLDEN_PATH = "tests/golden/pipeline_dubai_kinematic_cap1.json"
RECOMMENDATIONS_GOLDEN_PATH = "tests/golden/recommendations_dubai_kinematic_cap1.json"


def _load_golden(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        pytest.fail(
            f"{path} not found -- run `python -m tests.generate_golden` first "
            "(deliberately, not automatically: see that script's own docstring)."
        )


def test_golden_file_metadata_present():
    """The golden file's own self-description must be complete enough to
    attribute a future failure -- checked directly, not assumed."""
    golden = _load_golden(PIPELINE_GOLDEN_PATH)
    meta = golden.get("_meta", {})
    for key in ("git_commit_hash", "generated_at_utc", "data_file",
                "sideslip_source", "accuracy_cap"):
        assert key in meta and meta[key] not in (None, ""), f"golden file _meta missing/empty {key!r}"
    assert meta["sideslip_source"] == "kinematic"
    assert meta["accuracy_cap"] == 1


def test_pipeline_output_matches_golden(pipeline_result):
    """summarise_corners' complete output, recomputed now, against the
    pinned golden snapshot."""
    golden = _load_golden(PIPELINE_GOLDEN_PATH)
    got = {"summaries": pipeline_result["summaries"]}
    expected = {"summaries": golden["summaries"]}
    diffs = diff_json(got, expected)
    assert not diffs, (
        f"{len(diffs)} field(s) differ from tests/golden/pipeline_dubai_kinematic_cap1.json "
        f"(golden generated at commit {golden['_meta']['git_commit_hash']}, "
        f"{golden['_meta']['generated_at_utc']}):\n" +
        "\n".join(f"  {p}: got={a!r} expected={b!r}" for p, a, b in diffs[:30]) +
        (f"\n  ... and {len(diffs) - 30} more" if len(diffs) > 30 else "")
    )


def test_pipeline_corner_count_matches_golden(pipeline_result):
    """Cheap, fast-failing sanity check ahead of the full field-by-field
    diff above -- if this fails, the diff above will be enormous and this
    gives a faster, clearer first signal (corner detection/count changed,
    not just some numeric field)."""
    golden = _load_golden(PIPELINE_GOLDEN_PATH)
    assert len(pipeline_result["summaries"]) == len(golden["summaries"])


def test_recommendations_output_matches_golden(pipeline_result):
    """Same regression check for the recommendation engine's output on
    the same outing/configuration. Reuses OutingForm._classify_corner
    unmodified (self=None call, the same precedent core/weekend_pdf_
    export.py already uses in production) so this test can never
    silently drift from what the app itself would classify -- see
    tests/generate_golden.py for why this needs importing ui/views/
    outing_form.py despite the rest of this suite staying Qt-free.
    """
    try:
        from ui.views.outing_form import OutingForm
    except ImportError as e:
        pytest.skip(f"ui.views.outing_form not importable in this environment ({e}) -- "
                     "recommendation-engine golden check skipped, see report 'chose not to do'")

    from modules.recommendation import generate_recommendations, load_recommendations_config

    def classify_fn(summary):
        return OutingForm._classify_corner(None, summary)

    golden = _load_golden(RECOMMENDATIONS_GOLDEN_PATH)
    rec_config = load_recommendations_config()
    results = generate_recommendations(
        pipeline_result["summaries"], classify_fn, feedback_data={}, setup_data=None,
        config=rec_config, outing=None, driving_level=None,
    )
    diffs = diff_json({"recommendations": results}, {"recommendations": golden["recommendations"]})
    assert not diffs, (
        f"{len(diffs)} field(s) differ from tests/golden/recommendations_dubai_kinematic_cap1.json:\n" +
        "\n".join(f"  {p}: got={a!r} expected={b!r}" for p, a, b in diffs[:30])
    )
