# Fresh-session work package, Phase 4e -- golden-value regression for
# the two new auto-fit modes. Same REGRESSION-NOT-CORRECTNESS caveat as
# tests/test_golden_pipeline.py: pins CURRENT output, makes a future
# unintended change visible, claims nothing about correctness. The
# kinematic golden (tests/golden/pipeline_dubai_kinematic_cap1.json)
# and its own test file are UNTOUCHED by this package -- these are new,
# separate golden files (tests/golden/pipeline_dubai_ekf_auto_*_cap1.
# json, generated by tests/generate_golden_auto_modes.py) and a new
# fixture, not a modification of the existing kinematic-only fixture.

import json

import pytest

from modules.csv_parser import parse_csv
from modules.stability_analysis import (
    load_parameters, prepare_vehicle_state,
    estimate_slip_angles, estimate_lateral_forces, estimate_cornering_stiffness,
    estimate_yaw_moment_stability, estimate_vertical_loads, summarise_corners,
)
from modules.accuracy_resolution import resolve_accuracy, apply_resolved_vehicle
from modules.tyre_fit_auto import resolve_sideslip_beta
from tests._json_utils import diff_json

RAW_FILE = "C:/UNI/Bachelorarbeit/Data/Sample/Sample_Dubai.txt"
FIXED_CAP = 1
GOLDEN_PATHS = {
    "ekf_auto_dugoff": "tests/golden/pipeline_dubai_ekf_auto_dugoff_cap1.json",
    "ekf_auto_pacejka": "tests/golden/pipeline_dubai_ekf_auto_pacejka_cap1.json",
}


@pytest.fixture(scope="module")
def auto_mode_results():
    """Both auto modes' full pipeline output, computed once for this
    module (each involves a real fit chain, ~15-25s) via the exact
    production wiring function (resolve_sideslip_beta), same
    call-order/arguments as StabilityAnalysisThread.run().
    """
    params = load_parameters()
    resolved = resolve_accuracy(params, setup_data=None, cap=FIXED_CAP)
    effective_params = apply_resolved_vehicle(params, resolved)
    data = parse_csv(RAW_FILE)
    state = prepare_vehicle_state(data["channels"], effective_params)

    results = {}
    for mode in GOLDEN_PATHS:
        beta, fit_manifest, gate_verdict, fallback_used, fallback_reason = resolve_sideslip_beta(
            state, effective_params, data, mode, csv_path=RAW_FILE
        )
        slip = estimate_slip_angles(state, beta, effective_params)
        forces = estimate_lateral_forces(state, effective_params)
        cs = estimate_cornering_stiffness(slip, forces, state, effective_params)
        stab = estimate_yaw_moment_stability(state, beta, effective_params, data.get("laps", []))
        fz = estimate_vertical_loads(state, forces, effective_params)
        corners = data.get("corners", [])
        summaries = summarise_corners(corners, cs, stab, state, fz=fz, lap_filter=None)
        results[mode] = {
            "summaries": summaries, "fallback_used": fallback_used,
            "fallback_reason": fallback_reason, "gate_verdict": gate_verdict,
        }
    return results


def _load_golden(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        pytest.fail(
            f"{path} not found -- run `python -m tests.generate_golden_auto_modes` first "
            "(deliberately, not automatically)."
        )


@pytest.mark.parametrize("mode", list(GOLDEN_PATHS))
def test_golden_file_metadata_present(mode):
    golden = _load_golden(GOLDEN_PATHS[mode])
    meta = golden.get("_meta", {})
    for key in ("git_commit_hash", "generated_at_utc", "data_file", "sideslip_source", "accuracy_cap"):
        assert key in meta and meta[key] not in (None, ""), f"golden file _meta missing/empty {key!r}"
    assert meta["sideslip_source"] == mode
    assert meta["accuracy_cap"] == 1


@pytest.mark.parametrize("mode", list(GOLDEN_PATHS))
def test_auto_mode_did_not_fall_back(auto_mode_results, mode):
    """A golden comparison against a FALLBACK run would silently pin
    kinematic numbers under an 'ekf_auto_*' label -- checked explicitly
    so that failure mode reads as its own clear assertion, not a buried
    diff in the summaries comparison below."""
    r = auto_mode_results[mode]
    assert not r["fallback_used"], (
        f"{mode} fell back to kinematic on this run ({r['fallback_reason']}) -- "
        "the golden comparison below would be meaningless under fallback"
    )


@pytest.mark.parametrize("mode", list(GOLDEN_PATHS))
def test_auto_mode_output_matches_golden(auto_mode_results, mode):
    golden = _load_golden(GOLDEN_PATHS[mode])
    got = {"summaries": auto_mode_results[mode]["summaries"]}
    expected = {"summaries": golden["summaries"]}
    diffs = diff_json(got, expected)
    assert not diffs, (
        f"{len(diffs)} field(s) differ from {GOLDEN_PATHS[mode]} "
        f"(golden generated at commit {golden['_meta']['git_commit_hash']}, "
        f"{golden['_meta']['generated_at_utc']}):\n" +
        "\n".join(f"  {p}: got={a!r} expected={b!r}" for p, a, b in diffs[:30]) +
        (f"\n  ... and {len(diffs) - 30} more" if len(diffs) > 30 else "")
    )


@pytest.mark.parametrize("mode", list(GOLDEN_PATHS))
def test_auto_mode_corner_count_matches_golden(auto_mode_results, mode):
    golden = _load_golden(GOLDEN_PATHS[mode])
    assert len(auto_mode_results[mode]["summaries"]) == len(golden["summaries"])
