# WP-PERF Phase 0b: byte-identity reference capture. Runs the production
# call sequence (same as diagnostics/inspect_pipeline_wall_times.py, which
# is itself diagnostics/inspect_frame_stage2_parity.py's own call shape,
# one call at a time) up through estimate_cornering_stiffness and
# estimate_longitudinal_stiffness on both real sessions, live config,
# and dumps every key of both output dicts to a gitignored .npz per
# session. `[keep-reproduces]` -- WP-PERF's frozen pass-1 byte-identity
# baseline; every phase's proof step (1b/2b) compares its own re-run
# against these files via compare_wp_perf_reference.py. Read-only:
# nothing in modules/ is touched, no config/production change.
#
# The frozen pass-1 files (_wp_perf_reference_dubai.npz / _v3.npz, no
# suffix) are the hard-bar ground truth and are never regenerated by a
# later phase -- a later phase's own proof run passes a suffix (e.g.
# `--suffix _phase1a`) so its output lands in a DIFFERENT file and gets
# compared against the frozen one, never overwrites it.

import sys

import numpy as np

from modules.csv_parser import parse_csv
from modules.stability_analysis import (
    load_parameters, prepare_vehicle_state, load_car_data,
    estimate_slip_angles, estimate_lateral_forces, estimate_cornering_stiffness,
)
from modules.longitudinal_forces import estimate_longitudinal_forces, estimate_slip_ratio
from modules.longitudinal_stiffness import estimate_longitudinal_stiffness
from modules.accuracy_resolution import resolve_accuracy, apply_resolved_vehicle
from modules.tyre_fit_auto import resolve_sideslip_beta
from diagnostics.inspect_frame_stage2_parity import DUBAI_FILE, V3_FILE, FIXED_CAP


def capture(raw_file, label, suffix=""):
    params = load_parameters()
    resolved = resolve_accuracy(params, setup_data=None, cap=FIXED_CAP)
    effective_params = apply_resolved_vehicle(params, resolved)
    sideslip_source = effective_params["stability_estimation"].get("sideslip_source", "kinematic")

    data = parse_csv(raw_file)
    state = prepare_vehicle_state(data["channels"], effective_params)
    beta, fit_manifest, gate_verdict, fallback_used, fallback_reason = resolve_sideslip_beta(
        state, effective_params, data, sideslip_source, csv_path=raw_file
    )
    if fallback_used:
        print(f"  NOTE: {label} fell back to kinematic beta: {fallback_reason}")

    slip = estimate_slip_angles(state, beta, effective_params)
    forces = estimate_lateral_forces(state, effective_params)
    cs = estimate_cornering_stiffness(slip, forces, state, effective_params)

    long_forces = estimate_longitudinal_forces(state, data["channels"], effective_params)
    slip_ratio = estimate_slip_ratio(state, data["channels"], effective_params)
    ls = estimate_longitudinal_stiffness(long_forces, slip_ratio, state, effective_params)

    out = {f"cs__{k}": np.asarray(v) for k, v in cs.items()}
    out.update({f"ls__{k}": np.asarray(v) for k, v in ls.items()})
    path = f"diagnostics/_wp_perf_reference_{label}{suffix}.npz"
    np.savez(path, **out)
    print(f"{label}: wrote {path} ({len(out)} arrays)")
    return path


if __name__ == "__main__":
    suffix_arg = sys.argv[1] if len(sys.argv) > 1 else ""
    if suffix_arg == "":
        print("WARNING: no suffix given -- this OVERWRITES the frozen pass-1 "
              "reference. Pass a suffix (e.g. _phase1a) for a later phase's "
              "own proof run.")
    capture(DUBAI_FILE, "dubai", suffix=suffix_arg)
    capture(V3_FILE, "v3", suffix=suffix_arg)
