# Damper wheel-load showcase (read-only, no production/config changes).
# Computes the numbers block reported alongside this script's own run,
# and renders 2 new PRINT figures (fastest-lap 4-corner trace, one heavy-
# braking zoom) into diagnostics/plots_v3/ -- the third deliverable item
# (static-vs-damper comparison, front+rear) reuses the two figures
# already generated by inspect_v3_wheel_load_comparison_figure.py and
# inspect_v3_wheel_load_reconstruction_figure.py, not regenerated here
# (nothing in modules/wheel_loads.py changed since they were made).
#
# Uses the three-tier cascade throughout (damper-measured -> reconstructed
# -> static-split, modules.wheel_loads.combine_with_reconstruction_and_
# fallback) so FR reads as "reconstructed" wherever the corrupted
# log_dms_dam_fr channel would otherwise force a plain static guess.
#
# Reuses core/figure_render.py's _new_figure/_apply_theme/_draw_corner_
# bands/save_png (the same PRINT-theme building blocks render_lap_figure
# uses) rather than inventing new style constants -- the wheel-load panel
# drawing itself is new (no existing renderer draws Fz).

import os

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from core import plot_style as ps
from core.figure_render import _new_figure, _apply_theme, _draw_corner_bands, save_png
from modules.csv_parser import parse_csv
from modules.stability_analysis import (
    load_parameters, load_car_data, prepare_vehicle_state, estimate_lateral_forces,
    estimate_vertical_loads,
)
from modules.wheel_loads import (
    estimate_wheel_loads_from_dampers, estimate_session_corrected_axle_totals, reconstruct_missing_corner,
    combine_with_reconstruction_and_fallback, CORNERS,
)

RAW_FILE = "GT3_PRC_MLA-v3.txt"
OUT_DIR = "diagnostics/plots_v3"
WHEEL_LABELS = {"fl": "FL", "fr": "FR", "rl": "RL", "rr": "RR"}


def _corner_at_time(corners, t):
    for c in corners:
        segs = c["segments"]
        t0, t1 = segs["entry_1_brake"][0], segs["exit_5"][1]
        if t0 <= t <= t1:
            return c.get("stable_corner_id")
    return None


def main():
    data = parse_csv(RAW_FILE)
    params = load_parameters()
    car_data = load_car_data()
    state = prepare_vehicle_state(data["channels"], params)
    if state is None or car_data is None:
        print("cannot run -- missing state or car_data.json")
        return

    forces = estimate_lateral_forces(state, params)
    fz_static = estimate_vertical_loads(state, forces, params)
    static_fallback_fz = {c: fz_static[f"fz_{c}_N"] for c in CORNERS}
    damper_result = estimate_wheel_loads_from_dampers(state, data["channels"], params, car_data)
    # Session-corrected axle-total model (thesis_notes.md "Closing the
    # reconstruction's aero gap") feeds ONLY the reconstruction tier below
    # -- the plain static-split fallback (static_fallback_fz, used only
    # when BOTH corners of an axle are damper-invalid) is untouched.
    session_corrected = estimate_session_corrected_axle_totals(state, damper_result, params)
    print(f"session-corrected axle-total model: mass_kg_session={session_corrected['mass_kg_session']:.1f} kg "
          f"(config was {params['vehicle']['mass_kg']:.1f} kg), "
          f"c_session={session_corrected['c_session_N_per_mps2']:.4f} N/(m/s)^2, "
          f"aero_front_fraction={session_corrected['aero_front_fraction']:.2f}\n")
    fz_axle_totals = {"fz_f_N": session_corrected["fz_f_N"], "fz_r_N": session_corrected["fz_r_N"]}
    combined = combine_with_reconstruction_and_fallback(damper_result, fz_axle_totals, static_fallback_fz)

    t = state["time"]
    v = state["v_mps"]
    ax = state["ax_mps2"]
    ay = state["ay_mps2"]
    g = 9.81
    moving = v >= params["stability_estimation"]["moving_speed_min_mps"]
    straight = moving & (np.abs(ax) < 0.5) & (np.abs(ay) < 0.5)

    vp = params["vehicle"]
    config_kg = {"fl": vp["corner_weights"]["FL_kg"], "fr": vp["corner_weights"]["FR_kg"],
                 "rl": vp["corner_weights"]["RL_kg"], "rr": vp["corner_weights"]["RR_kg"]}

    print("=" * 78)
    print("NUMBERS BLOCK")
    print("=" * 78)

    print("\n--- corner weights: config (static) vs measured straight-line mean (kg) ---")
    total_config_kg = sum(config_kg.values())
    total_measured_kg = 0.0
    for c in CORNERS:
        measured_kg = float(np.mean(combined[c]["fz_N"][straight])) / g
        total_measured_kg += measured_kg
        tag = " [reconstructed]" if c == "fr" else ""
        print(f"  {WHEEL_LABELS[c]}{tag}: config={config_kg[c]:.1f} kg, measured={measured_kg:.1f} kg, "
              f"delta={measured_kg - config_kg[c]:+.1f} kg")
    residual_pct = (total_measured_kg - total_config_kg) / total_config_kg * 100.0
    print(f"  TOTAL: config={total_config_kg:.1f} kg, measured={total_measured_kg:.1f} kg "
          f"({residual_pct:+.1f}%, aero-consistent residual per Phase 5's own v^2 regression -- "
          f"no aero term exists in the config-only comparison)")

    print("\n--- peak load per wheel over the whole session (kN) ---")
    for c in CORNERS:
        fz = combined[c]["fz_N"]
        idx = int(np.nanargmax(fz))
        cid = _corner_at_time(data["corners"], t[idx])
        location = f"corner C{cid}" if cid is not None else "outside any detected corner bracket (braking zone or straight)"
        print(f"  {WHEEL_LABELS[c]}: peak={fz[idx]/1000.0:.2f} kN at t={t[idx]:.2f}s, v={v[idx]*3.6:.0f} km/h, "
              f"ax={ax[idx]:.1f} m/s^2, ay={ay[idx]:.1f} m/s^2 -- {location}")

    print("\n--- max longitudinal transfer event (heaviest braking) ---")
    idx_brake = int(np.argmin(ax))
    front_at_brake = combined["fl"]["fz_N"][idx_brake] + combined["fr"]["fz_N"][idx_brake]
    rear_at_brake = combined["rl"]["fz_N"][idx_brake] + combined["rr"]["fz_N"][idx_brake]
    front_straight_mean = float(np.mean(combined["fl"]["fz_N"][straight] + combined["fr"]["fz_N"][straight]))
    rear_straight_mean = float(np.mean(combined["rl"]["fz_N"][straight] + combined["rr"]["fz_N"][straight]))
    cid = _corner_at_time(data["corners"], t[idx_brake])
    print(f"  heaviest braking sample: t={t[idx_brake]:.2f}s, ax={ax[idx_brake]:.2f} m/s^2, "
          f"v={v[idx_brake]*3.6:.0f} km/h, corner={cid if cid is not None else 'braking zone, no bracket'}")
    print(f"  front axle: {front_at_brake/1000.0:.2f} kN (straight-line mean {front_straight_mean/1000.0:.2f} kN, "
          f"gain {(front_at_brake - front_straight_mean)/1000.0:+.2f} kN)")
    print(f"  rear axle: {rear_at_brake/1000.0:.2f} kN (straight-line mean {rear_straight_mean/1000.0:.2f} kN, "
          f"change {(rear_at_brake - rear_straight_mean)/1000.0:+.2f} kN)")

    print("\n--- max lateral transfer event (fastest corner, highest |ay|) ---")
    idx_corner = int(np.argmax(np.abs(ay)))
    cid = _corner_at_time(data["corners"], t[idx_corner])
    outside_is_right = ay[idx_corner] > 0
    front_outside = combined["fr"]["fz_N"][idx_corner] if outside_is_right else combined["fl"]["fz_N"][idx_corner]
    front_inside = combined["fl"]["fz_N"][idx_corner] if outside_is_right else combined["fr"]["fz_N"][idx_corner]
    rear_outside = combined["rr"]["fz_N"][idx_corner] if outside_is_right else combined["rl"]["fz_N"][idx_corner]
    rear_inside = combined["rl"]["fz_N"][idx_corner] if outside_is_right else combined["rr"]["fz_N"][idx_corner]
    print(f"  fastest-|ay| sample: t={t[idx_corner]:.2f}s, ay={ay[idx_corner]:.2f} m/s^2 "
          f"({'right-hand' if outside_is_right else 'left-hand'} corner), v={v[idx_corner]*3.6:.0f} km/h, "
          f"corner={cid if cid is not None else 'no bracket at this instant'}")
    print(f"  front: outside={front_outside/1000.0:.2f} kN, inside={front_inside/1000.0:.2f} kN, "
          f"split={front_outside/1000.0 - front_inside/1000.0:+.2f} kN")
    print(f"  rear:  outside={rear_outside/1000.0:.2f} kN, inside={rear_inside/1000.0:.2f} kN, "
          f"split={rear_outside/1000.0 - rear_inside/1000.0:+.2f} kN")

    print("\n--- aero: extra load at 200/250 km/h from Phase 5's own regression ---")
    total_fz = sum(combined[c]["fz_N"] for c in CORNERS)
    mask = moving & (np.abs(ay) < 1.5)
    X = np.column_stack([np.ones(mask.sum()), ax[mask], v[mask] ** 2])
    y = total_fz[mask]
    coeffs, _, _, _ = np.linalg.lstsq(X, y, rcond=None)
    a_coef, b_coef, c_coef = coeffs
    resid_std = float(np.std(y - X @ coeffs))
    for kmh in (200.0, 250.0):
        v_mps = kmh / 3.6
        extra_N = c_coef * v_mps ** 2
        print(f"  at {kmh:.0f} km/h: extra load = {extra_N/1000.0:.2f} kN "
              f"+/- {resid_std/1000.0:.2f} kN (data-scatter band from the fit's own residual std, "
              f"NOT a formal parameter confidence interval; R^2=0.79, c={c_coef:.4f} N/(m/s)^2)")

    print("\n" + "=" * 78)
    print("FIGURES")
    print("=" * 78)

    # --- figure (a): full fastest-lap 4-corner trace, established per-lap style
    fastest = next((lap for lap in data["laps"] if lap.get("is_fastest")), None)
    sanity_notes_a = []
    if fastest is None:
        print("no fastest lap found -- skipping figure (a)")
    else:
        s_m = state["s_m"]
        lo = np.searchsorted(t, fastest["start_time"])
        hi = np.searchsorted(t, fastest["end_time"])
        sl = slice(lo, hi)
        order = np.argsort(s_m[sl])
        lap_s = s_m[sl][order]

        corner_bands = []
        seen_ids = set()
        for c in data["corners"]:
            cid = c.get("stable_corner_id")
            if cid is None or cid in seen_ids or c.get("lap_number") != fastest["lap_number"]:
                continue
            seen_ids.add(cid)
            b0, b1 = c.get("bracket_start_m"), c.get("bracket_end_m")
            if b0 is not None and b1 is not None and b1 > b0:
                corner_bands.append((b0, b1, cid))

        fig = _new_figure(ps.PRINT_WIDTH_CM, ps.PRINT_HEIGHT_CM_VERDICT, ps.PRINT)
        fig.get_layout_engine().set(w_pad=0.0, h_pad=0.03, wspace=0.0, hspace=0.02, rect=(0.06, 0.0, 1.0, 1.0))
        gs = fig.add_gridspec(5, 1)
        axes = []
        ax0 = fig.add_subplot(gs[0, 0])
        ax0.plot(lap_s, (v[sl][order]) * 3.6, color=ps.LAP_PALETTE[0], linewidth=1.0)
        ax0.set_ylabel("Speed (km/h)")
        axes.append(ax0)
        for row, c in enumerate(CORNERS, start=1):
            axp = fig.add_subplot(gs[row, 0], sharex=ax0)
            fz_kn = combined[c]["fz_N"][sl][order] / 1000.0
            axp.plot(lap_s, fz_kn, color=ps.LAP_PALETTE[1 if c == "fr" else 0], linewidth=1.0)
            label = f"{WHEEL_LABELS[c]} Fz (kN)" + (" [reconstructed]" if c == "fr" else "")
            axp.set_ylabel(label)
            axes.append(axp)
            if np.any(np.isnan(fz_kn)):
                sanity_notes_a.append(f"{WHEEL_LABELS[c]}: NaN samples present in this lap window")
            if fz_kn.size and np.nanmin(fz_kn) < 0:
                sanity_notes_a.append(f"{WHEEL_LABELS[c]}: dips negative (min {np.nanmin(fz_kn):.2f} kN) -- unphysical, flagged not corrected")
        axes[-1].set_xlabel("Track position s (m)")
        for i, axp in enumerate(axes):
            _draw_corner_bands(axp, corner_bands, label_above=(i == 0))
        fig.suptitle(f"Fastest lap ({fastest['lap_number']}) -- 4-corner Fz trace, GT3_PRC_MLA-v3",
                     color=ps.PRINT["text"], fontsize=ps.PRINT_FONT_SIZE_PT + 1)
        _apply_theme(fig, axes, ps.PRINT)
        os.makedirs(OUT_DIR, exist_ok=True)
        path_a = os.path.join(OUT_DIR, f"wheel_load_showcase_fastest_lap{fastest['lap_number']}.png")
        save_png(fig, path_a)
        print(f"(a) saved {path_a}")
        print(f"    sanity notes: {sanity_notes_a if sanity_notes_a else 'none'}")

    # --- figure (b): one heavy-braking zone zoomed, loads + ax vs time
    sanity_notes_b = []
    margin_s = 1.5
    lo_t = max(t[idx_brake] - margin_s, t[0])
    hi_t = min(t[idx_brake] + margin_s, t[-1])
    lo_i = np.searchsorted(t, lo_t)
    hi_i = np.searchsorted(t, hi_t)
    sl_b = slice(lo_i, hi_i)
    t_rel = t[sl_b] - t[idx_brake]

    fig, axes = plt.subplots(2, 1, figsize=(ps.PRINT_WIDTH_CM / 2.54, 14.0 / 2.54),
                              constrained_layout=True, sharex=True)
    theme = ps.PRINT
    fig.patch.set_facecolor(theme["bg"])
    ax_load, ax_ax = axes
    ax_load.set_facecolor(theme["bg"])
    for i, c in enumerate(CORNERS):
        fz_kn = combined[c]["fz_N"][sl_b] / 1000.0
        ax_load.plot(t_rel, fz_kn, color=ps.LAP_PALETTE[i], linewidth=1.2,
                     label=WHEEL_LABELS[c] + (" [reconstructed]" if c == "fr" else ""))
        if fz_kn.size and np.nanmin(fz_kn) < 0:
            sanity_notes_b.append(f"{WHEEL_LABELS[c]}: dips negative (min {np.nanmin(fz_kn):.2f} kN) in this braking zoom")
    ax_load.set_ylabel("Fz (kN)")
    ax_load.axvline(0.0, color=theme["text_muted"], linewidth=0.8, linestyle=":")
    ax_ax.set_facecolor(theme["bg"])
    ax_ax.plot(t_rel, ax[sl_b], color=theme["text"], linewidth=1.2)
    ax_ax.axvline(0.0, color=theme["text_muted"], linewidth=0.8, linestyle=":")
    ax_ax.set_ylabel("ax (m/s^2)")
    ax_ax.set_xlabel("Time relative to peak braking (s)")
    for a_ in axes:
        a_.tick_params(colors=theme["text"], labelsize=ps.PRINT_FONT_SIZE_PT)
        a_.grid(True, alpha=theme["grid_alpha"], color=theme["grid"])
        for spine in a_.spines.values():
            spine.set_color(theme["text_muted"])
    leg = ax_load.legend(fontsize=ps.PRINT_FONT_SIZE_PT * 0.8, framealpha=0.85, ncol=2)
    leg.get_frame().set_facecolor(theme["bg"])
    fig.suptitle(f"Heaviest braking zone, t={t[idx_brake]:.1f}s (ax={ax[idx_brake]:.1f} m/s^2) -- "
                 f"wheel loads + ax, GT3_PRC_MLA-v3", color=theme["text"], fontsize=ps.PRINT_FONT_SIZE_PT)
    path_b = os.path.join(OUT_DIR, "wheel_load_showcase_heavy_braking_zoom.png")
    save_png(fig, path_b)
    print(f"(b) saved {path_b}")
    print(f"    sanity notes: {sanity_notes_b if sanity_notes_b else 'none'}")

    print("\n(c) reusing existing figures, not regenerated (no wheel_loads.py change since they were made):")
    print("    diagnostics/plots_v3/wheel_load_comparison_C12_lap8.png (rear axle, measured vs static-split)")
    print("    diagnostics/plots_v3/wheel_load_reconstruction_C12_lap8.png (front axle, measured FL vs reconstructed FR)")


if __name__ == "__main__":
    main()
